const PREFIX = 'STUDENT'

export const CREATE_STUDENT = `${PREFIX}/CREATE_STUDENT`
export const UPDATE_STUDENT = `${PREFIX}/UPDATE_STUDENT`
export const DELETE_STUDENT = `${PREFIX}/DELETE_STUDENT`
export const SELECT_STUDENT = `${PREFIX}/SELECT_STUDENT`
